### ISSUE TITLE
Can't find the plugin options

### ISSUE THREAD

**Issue by gonzalo-massa** [RoboMagus/OctoPrint-PreheatHelper#1]
Hi, I've just installed the plugin, but I couldn't find where to set the default preheat temperatures.

I've checked the temperatures and control tabs, and the OctoPrint's configuration modal, under the "Plugins" menú section I don't se any new item.

I don't have any theme installed.

**Comment by gatonero** [comment]
Same here.

**Comment by RoboMagus** [comment]
~~Could you please share the installation logs so I can check if something failed there?~~

~~And also please enable debug logging for this plugin ([see how to do so here](https://docs.octoprint.org/en/master/bundledplugins/logging.html)) and share those logs.~~
~~It's likely something went wrong during initialization that will show up in either of those logs.~~

**EDIT:**
It seems no release was created yet for v0.1.0. Could you try re-installing the plugin and reporting back if that solves your issue?

**Comment by gatonero** [comment]
Yeah, thank you! Now I see the options under OctoPrint Settings. And it's working :-)
Here is the installation log:

`Installiere Plugin von https://github.com/RoboMagus/OctoPrint-PreheatHelper/archive/master.zip...
/home/cs/oprint/bin/python3 -m pip --disable-pip-version-check install file:///tmp/tmpm9q77ptg/OctoPrint-PreheatHelper-master.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmpm9q77ptg/OctoPrint-PreheatHelper-master.zip
Requirement already satisfied: OctoPrint in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint-PreheatHelper==0.1.0) (1.7.3)
Requirement already satisfied: pylru<2,>=1.2 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.2.0)
Requirement already satisfied: Click<8,>=7.1.2 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (7.1.2)
Requirement already satisfied: itsdangerous<2,>=1.1.0 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.1.0)
Requirement already satisfied: OctoPrint-PiSupport>=2021.10.28 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2022.3.28)
Requirement already satisfied: unidecode in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (0.4.21)
Requirement already satisfied: pathvalidate<3,>=2.4.1 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2.5.0)
Requirement already satisfied: OctoPrint-FirmwareCheck>=2021.10.11 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2021.10.11)
Requirement already satisfied: emoji<2,>=1.4.2 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.7.0)
Requirement already satisfied: wrapt<1.13,>=1.12.1 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.12.1)
Requirement already satisfied: werkzeug<2,>=1.0.1 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.0.1)
Requirement already satisfied: psutil<6,>=5.8 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (5.8.0)
Requirement already satisfied: pyserial<4,>=3.4 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (3.5)
Requirement already satisfied: feedparser<7,>=6.0.8 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (6.0.8)
Requirement already satisfied: filetype<2,>=1.0.7 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.0.7)
Requirement already satisfied: Jinja2<3,>=2.11.3 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2.11.3)
Requirement already satisfied: markupsafe<2.0,>=1.1 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.1.1)
Requirement already satisfied: blinker<2,>=1.4 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.4)
Requirement already satisfied: Flask-Assets<3,>=2.0 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2.0)
Requirement already satisfied: colorlog<6,>=5.0.1 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (5.0.1)
Requirement already satisfied: zeroconf<0.34,>=0.33 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (0.33.4)
Requirement already satisfied: regex in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2020.11.13)
Requirement already satisfied: zipstream-new<1.2,>=1.1.8 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.1.8)
Requirement already satisfied: watchdog==0.10.4 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (0.10.4)
Requirement already satisfied: flask<2,>=1.1.4 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.1.4)
Requirement already satisfied: cachelib<0.2,>=0.1 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (0.1.1)
Requirement already satisfied: netifaces<1,>=0.11 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (0.11.0)
Requirement already satisfied: pkginfo<2,>=1.7.1 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.8.2)
Requirement already satisfied: Flask-Login<0.6,>=0.5 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (0.5.0)
Requirement already satisfied: markdown<3.2,>=3.1 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (3.1.1)
Requirement already satisfied: netaddr<0.9,>=0.8 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (0.8.0)
Requirement already satisfied: tornado<7,>=6 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (6.1)
Requirement already satisfied: sarge==0.1.6 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (0.1.6)
Requirement already satisfied: immutabledict<3,>=2.1 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2.2.1)
Requirement already satisfied: websocket-client<1,>=0.59 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (0.59.0)
Requirement already satisfied: OctoPrint-FileCheck>=2021.2.23 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2021.2.23)
Requirement already satisfied: Flask-Babel<2,>=1.0 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.0.0)
Requirement already satisfied: semantic-version<3,>=2.8.5 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2.8.5)
Requirement already satisfied: future<1,>=0.18.2 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (0.18.2)
Requirement already satisfied: PyYAML<6,>=5.4.1 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (5.4.1)
Requirement already satisfied: requests<3,>=2.26.0 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2.27.1)
Requirement already satisfied: sentry-sdk<2,>=1.3.1 in /home/cs/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.5.8)
Requirement already satisfied: pathtools>=0.1.1 in /home/cs/oprint/lib/python3.7/site-packages (from watchdog==0.10.4->OctoPrint->OctoPrint-PreheatHelper==0.1.0) (0.1.2)
Requirement already satisfied: sgmllib3k in /home/cs/oprint/lib/python3.7/site-packages (from feedparser<7,>=6.0.8->OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.0.0)
Requirement already satisfied: webassets>=2.0 in /home/cs/oprint/lib/python3.7/site-packages (from Flask-Assets<3,>=2.0->OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2.0)
Requirement already satisfied: pytz in /home/cs/oprint/lib/python3.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2020.5)
Requirement already satisfied: Babel>=2.3 in /home/cs/oprint/lib/python3.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2.9.0)
Requirement already satisfied: setuptools>=36 in /home/cs/oprint/lib/python3.7/site-packages (from markdown<3.2,>=3.1->OctoPrint->OctoPrint-PreheatHelper==0.1.0) (51.1.2)
Requirement already satisfied: idna<4,>=2.5 in /home/cs/oprint/lib/python3.7/site-packages (from requests<3,>=2.26.0->OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/cs/oprint/lib/python3.7/site-packages (from requests<3,>=2.26.0->OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.26.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/cs/oprint/lib/python3.7/site-packages (from requests<3,>=2.26.0->OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2020.12.5)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/cs/oprint/lib/python3.7/site-packages (from requests<3,>=2.26.0->OctoPrint->OctoPrint-PreheatHelper==0.1.0) (2.0.12)
Requirement already satisfied: six in /home/cs/oprint/lib/python3.7/site-packages (from websocket-client<1,>=0.59->OctoPrint->OctoPrint-PreheatHelper==0.1.0) (1.15.0)
Requirement already satisfied: ifaddr>=0.1.7 in /home/cs/oprint/lib/python3.7/site-packages (from zeroconf<0.34,>=0.33->OctoPrint->OctoPrint-PreheatHelper==0.1.0) (0.1.7)
Building wheels for collected packages: OctoPrint-PreheatHelper
Building wheel for OctoPrint-PreheatHelper (setup.py): started
Building wheel for OctoPrint-PreheatHelper (setup.py): finished with status 'done'
Created wheel for OctoPrint-PreheatHelper: filename=OctoPrint_PreheatHelper-0.1.0-py2.py3-none-any.whl size=5391 sha256=4be58744452dc8de01c8c2c038135b36ff4d47b0d28d5c04c24cdb9dfc2a39a7
Stored in directory: /tmp/pip-ephem-wheel-cache-_xs1k4p4/wheels/30/de/c6/0c9886fb4b517716bd935e5f89f75e73e72aa9d69ad904e13d
Successfully built OctoPrint-PreheatHelper
Installing collected packages: OctoPrint-PreheatHelper
Attempting uninstall: OctoPrint-PreheatHelper
Found existing installation: OctoPrint-PreheatHelper 0.1.0
Uninstalling OctoPrint-PreheatHelper-0.1.0:
Successfully uninstalled OctoPrint-PreheatHelper-0.1.0
Successfully installed OctoPrint-PreheatHelper-0.1.0
Fertig!`

**Comment by gonzalo-massa** [comment]
Hey

I've just uninstalled, and reinstalled again. It's working now but with a caveat: After installing the pluign, the modal has a "Reload" button. After reloading OctoPrint the config didn't show up anywhere... I had to restart OctoPrint in order to see the plugin activated.

So, I don't know anything about plugin development, but if there is a way for you to specify that the installation requires a reboot (instead of a page reload) to work, that should be the fix.

Anyway, I'll post the installation log if it's of any use for you: [installation-log.txt](https://github.com/RoboMagus/OctoPrint-PreheatHelper/files/8689327/installation-log.txt)

Thanks for developing the plugin :)

**Comment by RoboMagus** [comment]
Thanks for the updates both of you. Glad its now working.

Regarding the reload that is indeed something to do with Octoprint itself. Octoprint only loads new plugins after it is restarted.

Depending on your installation type this may not be as explicit as it would ideally be. I personally gave it much thought, as in my setup when I install a plugin Octoprint automatically restarts the service, which to be fair can also be quite annoying if you want to install multiple plugins for instance. Then it'll restart every time between each new installed plugin.

Thanks for creating this issue. At least now the plugin is actually available for those that are interested ;)
