### ISSUE TITLE
[FR]: Documentation

### ISSUE THREAD

**Issue by CameronMcGuffie** [RoboMagus/OctoPrint-PreheatHelper#2]
Can the documentation please be updated to include instructions on how to configure this plugin? I cannot seem to find the settings and want to change the initial temps.

P.S. Thanks for the great plugin!

**Comment by RoboMagus** [comment]
There should be an entry in the _plugin_ section of the settings menu as highlighted in the image below. (Note that your configuration options may not match the screenshot, as I've taken this example from my development setup).

![image](https://user-images.githubusercontent.com/68224306/168746457-59d48eab-4088-46c0-84c0-13c530a9aba0.png)

From there on out all available settings should be accessible to you. 
If this entry is not in there, please check if the plugin is installed correctly and try to restart Octoprint. 

I am planning to update the documentation later on, as I have to agree that the current information under [configuration](https://github.com/RoboMagus/OctoPrint-PreheatHelper#configuration) is not all that descriptive.
This will be postponed however until after I've added some more new features and revamped the settings menu.

**Comment by CameronMcGuffie** [comment]
Cheers, it looks like v1.8.0 has made this option appear in settings. Strange that it was not showing. Nice work on the plugin.

**Comment by nifty1a** [comment]
Just updated to Octoprint 1.8.1, and added this plugin, no settings entry is appearing for it, in the Plugins section

<img width="218" alt="image" src="https://user-images.githubusercontent.com/26446739/175029245-0a6911ce-ff52-43b4-b037-839697acb97c.png">

**Comment by nifty1a** [comment]
> Just updated to Octoprint 1.8.1, and added this plugin, no settings entry is appearing for it, in the Plugins section
> 
> <img alt="image" width="218" src="https://user-images.githubusercontent.com/26446739/175029245-0a6911ce-ff52-43b4-b037-839697acb97c.png">

Restarting Octprint completely rather rather just reloading interface,has made the settings option appear now
