### ISSUE TITLE
[BUG]: Install seemed to go fine, but then...

### ISSUE THREAD

**Issue by SoLongSidekick** [RoboMagus/OctoPrint-PreheatHelper#3]
I received [these messages](https://i.imgur.com/keV724F.png) once OP had restarted and I don't see any link for it in the plugins section of OP settings. Will try restarting everything from the router to the printer and let you know if this changes.

Printer: Creality CR-10v2
Board: Raspberry Pi 4
OP: v1.3.9
Other plugins:
Bed Visualizer, Cancel Options, Change Filament Plugin, Continuous Print, Cost Estimation, Cura Thumbnails, Dashboard, Detailed Progress, Display Z, Exclude Region, FileManager, Firmware Updater, Fullscreen Plugin, Heater Timeout, OctoApp, OctoEverywhere!, Octolapse, Preheat Button, PrettyGCode, PrintJobHistory, PrintTimeGenius, Progress Title, PSU Control, and Spoolmanager Plugin.

**Comment by RoboMagus** [comment]
Could you share the logs of this occurrence?

Based on the popup notifications in your screenshot it does not seem to be related to this plugin (nothing in this plugin produces popup notifications).

**Comment by RoboMagus** [comment]
Closing as unrelated to this plugin
